services:
  alocacao-backend:
    image: origemglobaltecnologia/logistica-pro-alocacao-service
    ports:
      - "8083:8080"
    networks:
      - logistica-net

  alocacao-frontend:
    image: origemglobaltecnologia/logistica-pro-alocacao-frontend
    ports:
      - "8084:80"
    networks:
      - logistica-net
    depends_on:
      - alocacao-backend

  item-service-backend:
    image: origemglobaltecnologia/logistica-pro-item-service
    ports:
      - "8085:8080"
    networks:
      - logistica-net

networks:
  logistica-net:
    driver: bridge
